on:
  push:
    branches:
      - "main" # change to the branch you wish to deploy from

permissions:
  contents: write-all
  pages: write
  id-token: write

jobs:
  deploy:
    name: Deploy Vetap to GitHub pages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: chrnorm/deployment-action@v2
      name: Create GitHub deployment
      id: deployment
      with:
        token: '${{ github.token }}'
        environment: production
        path: build # change to your build folder